modLoader = "javafml"
license = "LGPL v2"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Resource-Trimmer/issues"

[[mods]]
modId = "resourcetrimmer"
version = "26.2.0.0"
displayName = "ResourceTrimmer"
updateJSONURL = "https://updates.blamejared.com/get?n=resourcetrimmer&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/resource-trimmer"
logoFile = "logo_resourcetrimmer.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Reduces the size of resource locations on the network."

[[mixins]]
config = "resourcetrimmer.common.mixins.json"

[[mixins]]
config = "resourcetrimmer.neoforge.mixins.json"

[[dependencies.resourcetrimmer]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcetrimmer]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

